"use client";

import React, { useState } from "react";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { FileText, Download, Printer, CheckCircle } from "lucide-react";

export default function ReportsPage() {
  const [reportGenerated, setReportGenerated] = useState(false);

  return (
    <div className="p-6 space-y-6 font-mono">
      <PageHeader
        title="Plant Shift Reports & Transition Summaries"
        subtitle="Generate and export automated shift yield, grade change efficiency, and fiber savings reports."
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Report Generator Controls */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-cyan-400">
              <FileText className="w-4 h-4" /> GENERATE NEW REPORT
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <Select
              label="Select Report Type"
              options={[
                { label: "Shift A Grade Transition Yield Summary", value: "SHIFT_YIELD" },
                { label: "Monthly Off-Spec Waste Reduction Report", value: "WASTE_REDUCTION" },
                { label: "AI Closed-Loop Advisory Compliance Log", value: "AI_COMPLIANCE" },
              ]}
            />

            <Select
              label="Paper Machine Line"
              options={[
                { label: "PM-01 Paper Machine (Fine Writing)", value: "PM-01" },
                { label: "PM-02 Paper Machine (Linerboard)", value: "PM-02" },
              ]}
            />

            <div className="pt-2">
              <Button
                variant="cyan"
                size="sm"
                className="w-full flex items-center justify-center gap-2"
                onClick={() => setReportGenerated(true)}
              >
                <FileText className="w-4 h-4" /> GENERATE REPORT JSON/PDF
              </Button>
            </div>

            {reportGenerated && (
              <div className="p-3 bg-emerald-950/40 border border-emerald-500/40 text-emerald-300 text-xs">
                <div className="font-bold flex items-center gap-1.5 mb-1">
                  <CheckCircle className="w-4 h-4" /> REPORT GENERATED SUCCESSFUL
                </div>
                <div>Shift_A_Yield_Report_20260725.pdf is ready for download.</div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Recent Generated Reports Table (2 cols) */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>RECENT GENERATED REPORTS ARCHIVE</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>REPORT ID</TableHead>
                  <TableHead>TITLE</TableHead>
                  <TableHead>TYPE</TableHead>
                  <TableHead>GENERATED BY</TableHead>
                  <TableHead>DATE</TableHead>
                  <TableHead>ACTIONS</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-bold text-cyan-400">RPT-901</TableCell>
                  <TableCell>Shift A Grade Transition Yield Summary</TableCell>
                  <TableCell>SHIFT_YIELD</TableCell>
                  <TableCell>J. Miller</TableCell>
                  <TableCell>2026-07-25</TableCell>
                  <TableCell className="flex gap-2">
                    <Button variant="outline" size="sm"><Download className="w-3 h-3" /></Button>
                    <Button variant="ghost" size="sm"><Printer className="w-3 h-3" /></Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-bold text-gray-300">RPT-900</TableCell>
                  <TableCell>Monthly Off-Spec Waste Reduction</TableCell>
                  <TableCell>WASTE_REDUCTION</TableCell>
                  <TableCell>S. Chen</TableCell>
                  <TableCell>2026-07-24</TableCell>
                  <TableCell className="flex gap-2">
                    <Button variant="outline" size="sm"><Download className="w-3 h-3" /></Button>
                    <Button variant="ghost" size="sm"><Printer className="w-3 h-3" /></Button>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
